package pl.psk.upc.infrastructure.db.init;


import lombok.Getter;
import pl.psk.upc.infrastructure.entity.ProductType;

@Getter
public enum Products {
    ROUTER("TP-LINK Deco M4 Mesh WiFi System", 408.0, "Ciesz się mocnym i stabilnym sygnałem Wi-Fi jak nigdy wcześniej. Deco M4 wykorzystuje technologię TP-Link Mesh, aby zapewnić silny sygnał bezprzewodowy w każdym kącie twojego domu. Jednostki Deco współpracują ze sobą, aby tworzyć jednolitą sieć Wi-Fi.\n" +
            "\n" +
            "Dwie jednostki Deco pokrywają siecią powierzchnię do 260m2. Połączenia bezprzewodowe i opcjonalne łącze rezerwowe Ethernet łączą jednostki Deco, zapewniając jeszcze szybszą sieć i najbardziej płynny roaming. Potrzebujesz większego zasięgu Wi-Fi? Wystarczy dodać kolejną jednostkę Deco.", ProductType.INTERNET),
    ROUTER2("Router TP-LINK Archer AX50",349.99,"Dwupasmowa sieć w standardzie AX3000 to rozwiązanie technologiczne zastosowane w routerze TP-LINK Archer AX50. Model ten umożliwia zatem wykorzystanie obu zakresów częstotliwości połączenia z Internetem – zarówno 2,4, jak i 5 GHz. Takie połączenie gwarantuje wysoką przepustowość sieci domowej, co z kolei przekłada się na wygodę jej użytkowania. Dzięki routerowi TP-LINK Archer AX50 możesz bez przeszkód i limitów oglądać ulubione filmy, grać w gry online czy transmitować swoją rozgrywkę lub inne klipy wideo metodą przesyłania strumieniowego.", ProductType.INTERNET),
    ROUTER3("Router ASUS RT-AX58U V2 Wi-Fi 6 AX3000",538.9,"Sięgnij po standard Wi-Fi nowej generacji zapewniający przepustowość nawet 3000 Mb/s. ASUS RT-AX58U to dwuzakresowy router Wi-Fi 2x2 obsługujący najnowszy standard 802.11ax, zapewniając tym samym większą przepustowość i stabilność połączenia, przy podłączeniu wielu urządzeń sieciowych jednocześnie. Przy tym znacząco poprawia bezpieczeństwo Twoje i Twoich bliskich podczas korzystania z Internetu, wykorzystując w tym celu najnowsze rozwiązania na rynku.", ProductType.INTERNET),
    ROUTER4("Router TP-LINK Archer AX53",349.0,"Dwupasmowy, gigabitowy router Wi‑Fi 6 AX3000 TP-Link Archer AX53 oferuje prędkości nowej generacji dochodzące do 2402 Mb/s w paśmie 5 GHz i do 574 Mb/s w paśmie 2,4 GHz, zapewniając płynną transmisję i wyższe prędkości pobierania. Napędzany przez potężny, dwurdzeniowy procesor, ten w pełni wyposażony Router Wi-Fi 6 umożliwia wykonywanie wielu zadań działających płynnie w tym samym czasie. Korzystaj ze streamingu i gier jak nigdy przedtem.", ProductType.INTERNET),

    TV("TCL 58P635", 1999.0, "Żywe kolory, kontrast, wyraziste szczegóły i głębia to cechy, które tworzą obraz doskonały. Wszystko to dostarczy Ci telewizor TCL 58P635. Rozdzielczość 4K sprawia, że ekran wyświetla ponad 8 milionów pikseli, dzięki którym zobaczysz różnicę. Model ten sprawdzi się zarówno do oglądania filmów, czy seriali, ale także do grania. Został on wyposażony w złącze HDMI 2.1 z ALLM, dzięki któremu responsywność oraz jakość obrazu będą na bardzo wysokim poziomie. To bardzo ważny parametr dla każdego gracza. Co więcej, telewizor ma bezramkową konstrukcję, dzięki której obraz wciągnie Cię jeszcze bardziej. Natomiast Smart TV z platformą Google zapewni dostęp do różnych treści dla całej rodziny.", ProductType.TV),
    TV2("Sony KD-55X85K", 3999.0, "55-calowy telewizor Sony KD-55X85K został wyposażony w procesor 4K HDR Processor X1™ oraz technologie TRILUMINOS PRO™ i 4K X-Reality™ PRO, a także panel z odświeżaniem 120 Hz. Takie rozwiązanie pozwala, by urządzenie zachwyciło Cię urzekającymi kolorami dbającymi o niezwykły realizm. Ponadto telewizor zapewni Ci doskonałą rozdzielczość 4K niezależnie od źródła sygnału. Co więcej, o czysty dźwięk zadbają głośniki X-Balanced Speaker.", ProductType.TV),
    TV3("Xiaomi Mi LED TV A2 55\"", 2219.0, "Xiaomi Mi LED TV A2 to 55-calowy telewizor z wyświetlaczem Premium 4K Ultra HD. Szeroka gama kolorów, wsparcie HDR10, Dolby Vision i HLG, czy technologia MEMC sprawią, że obraz będzie wyrazisty i płynny. Urządzenie ma wbudowaną łączność Wi-Fi oraz Bluetooth. Dzięki temu możesz bez przeszkód korzystać z platformy Smart TV Android. Co więcej, telewizor obsługuje dekodowanie Dolby, a także DTS-HD, FLAC, czy AAC. Dzięki temu wysokiej jakości obraz jest uzupełniony o satysfakcjonujące brzmienie. Natomiast dekoder DVB-T2 pozwoli korzystać z nowego standardu telewizji naziemnej.", ProductType.TV),
    TV4("LG OLED65C21LA", 7990.0, "Pozwól, by 65-calowy ekran OLED evo telewizora LG OLED65C21LA stał się Twoim, oknem na nowy, jasny świat. Urządzenie zostało wyposażone w technologię Brightness Booster, która zapewni Ci o 20% większą jasność, będąc jednocześnie ekranem przyjaznym dla oczu. Ponadto telewizor oferuje Szybki procesor α9 Gen 5 AI o niesamowite prędkości, a także wsparcie sztucznej inteligencji ThinQ AI w języku polskim. Co więcej, LG OLED65C21LA da Ci również dostęp do wielu serwisów streamingowych takich jak: Amazon Prime, Apple TV+, Disney+, HBO MAX, czy Netflix. Dodatkowo dzięki technologiom Dolby Vision IQ oraz Dolby Atmos zastosowanym w telewizorze będziesz mógł cieszyć się prawdziwie kinowymi wrażeniami w Twoim salonie.", ProductType.TV),

    PHONE("Samsung Galaxy S23 8/256GB", 4799.0, "Samsung Galaxy S23 to smartfon kompletny. Szczególnie spodoba się użytkownikom, którzy preferują telefony bez problemu mieszczące się w kieszeni i jednocześnie potrzebują sprzętu z górnej półki. Wysoka wydajność, ogromne możliwości fotograficzne, świetny ekran, dobry czas pracy baterii i ładny design – to cechy, które najbardziej wyróżniają Galaxy S23.", ProductType.MOBILE),
    PHONE2("Motorola edge 40 5G 8/256GB", 2999.0, "Sprawdź, co może zaoferować Ci Motorola edge 40 5G 256 GB Coronet Blue. Elegancka obudowa pewnie leży w dłoni i świetnie komponuje się z każdym stylem. Nie obawiaj się przypadkowego zachlapania wodą. Klasa odporności IP68 dba, aby woda nie dostała się do wnętrza smartfona. Rób piękne i ciekawy zdjęcia, które zapiszą Twoje wspomnienia w wysokiej rozdzielczości.", ProductType.MOBILE),
    PHONE3("Samsung Galaxy M33 5G 6/128", 1099.0, "Sprawdź, co to znaczy zabawa bez ograniczeń. Odkrywaj wirtualny świat razem z Samsung Galaxy M33 5G 128 GB Green. Baw się, graj, oglądaj filmy i słuchaj muzyki z wydajnym smartfonem, którego bateria wystarczy Ci na cały dzień wrażeń. Twórz wspomnienia z pomocą telefonu i zapisuj je w najlepszej jakości, aby wracając do nich, poczuć się znów, jak na wakacjach. Czerp wiele radości z wyświetlanym treści na dużym ekranie z wysoką częstotliwością odświeżania, która nie pozwoli na żadne opóźnienia.", ProductType.MOBILE),
    PHONE4("Huawei P60 Pro 8/256GB", 5499.0, "Poznaj nową odsłonę serii smartfonów, która zrodziła się z piękna. Przed Tobą Huawei P60 Pro 256 GB czarny. Zapewne już wiesz, czego możesz spodziewać się po tym modelu. To wyjątkowa dbałość o jakość wykonania oraz najlepsze możliwości fotograficzne.\n" +
            "\n" +
            "Nowe aparaty XMAGE i obiektyw w regulowaną przysłoną pozwoli Ci poczuć się jak prawdziwy profesjonalista. Rób niesamowite zdjęcia w każdych warunkach i podziwiaj je na przestronny ekranie OLED o rozmiarze 6,67”. Moc do działania dostarczy Ci nowoczesny procesor, sporo pamięci RAM oraz wytrzymała bateria o sporej pojemności. Wybierz Huawei P60 Pro i poznaj jakość premium.", ProductType.MOBILE),
    PHONE5("Xiaomi POCO X5 Pro 5G 8/256GB", 1799.0, "Odkrywaj wirtualny świat razem z Xiaomi POCO X5 Pro 5G 256 GB Black i ciesz się jakością, jaką oferuje. Solidnie wykonana konstrukcja sprawdzi się doskonale podczas intensywnych i pełnych wrażeń dni. Poza tym smartfon dysponuje pojemną baterią, więc możesz korzystać z niego cały dzień. Dziel się treściami z przyjaciółmi, graj w nowe mobilne tytuły i prowadź długie rozmowy telefoniczne z bliskimi. Rób świetnej jakości zdjęcia i ciesz się z wyraźnym wspomnień wakacyjnego szaleństwa.", ProductType.MOBILE);


    private String productName;
    private double price;
    private String description;
    private ProductType productType;

    Products(String productName, double price, String description, ProductType productType) {
        this.productName = productName;
        this.price = price;
        this.description = description;
        this.productType = productType;
    }
}
